<!DOCTYPE html>
<html>
  <head>
    <title>E-karta</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/stil.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>E-karta!</h1>
        <p>Najbrži i najlakši način da naručite karte za putovanje vozom.</p>
        <form action="" method="post" name="podaci">
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4">
                <input type="textbox" class="form-control" name="tbPocetak" placeholder="Polazak" list="Stanice">
              </div>
              <div class="col-sm-4">
                <input type="textbox" class="form-control" name="tbOdrediste" placeholder="Odredište" list="Stanice">
              </div>
              <datalist id="Stanice">
                
                <option value="ADRANI">
                <option value="ADROVAC">
                <option value="ALEKSA ŠANTIĆ">
                <option value="ALEKSANDROVO PREDGRAĐE">
                <option value="ALEKSINAC">
                <option value="ALIBUNAR">
                <option value="BABIN POTOK">
                <option value="BAČKA TOPOLA">
                <option value="BAČKI MAGLIĆ">
                <option value="BAČKI VINOGRADI">
                <option value="BAD GASTEIN">
                <option value="BAD HOFGASTAIN">
                <option value="BADNJEVAC">
                <option value="BAGRDAN">
                <option value="BAJMOK">
                <option value="BALUGA">
                <option value="BANAT.MILOŠEVO POLJE">
                <option value="BANATSKI DESPOTOVAC">
                <option value="BANATSKI KARLOVAC">
                <option value="BANATSKO MILOŠEVO">
                <option value="BANATSKO NOVO SELO">
                <option value="BANJSKA">
                <option value="BANOVA JARUGA">
                <option value="BAR">
              </datalist>
              <div class="col-sm-4">
                <input type="date" class="form-control" name="Datum" placeholder="Datum" id="datepicker">
              </div>
            </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
              <input type="submit" class="form-control btn btn-primary" value="Pronađi &raquo;">
            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="progress progress-striped active">
            <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 30%">
            </div>
          </div>
          <h3>Ne postoji izabrana relacija!</h3>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Voz</th>
                  <th>Polazak </th>
                  <th>Datum</th>
                  <th>Dolazak</th>
                  <th>Datum dolaska</th>
                  <th>Putuje</th>
                  <th>Rang</th>
                  <th>Napomena</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                  <?php echo $this->layout()->content; ?>
                <tr>
                  <td>8001</td>
                  <td>06:28</td>
                  <td>08.12.2013</td>
                  <td>06:31</td>
                  <td>08.12.2013</td>
                  <td>00:03</td>
                  <td>Brzi</td>
                  <td></td>
                  <td><input type="button" class="btn btn-normal" value="Naruci"></td>
                </tr>
                <tr>
                  <td>8001</td>
                  <td>06:28</td>
                  <td>08.12.2013</td>
                  <td>06:31</td>
                  <td>08.12.2013</td>
                  <td>00:03</td>
                  <td>Brzi</td>
                  <td></td>
                  <td><input type="button" class="btn btn-normal" value="Naruci"></td>
                </tr>
                <tr>
                  <td>8001</td>
                  <td>06:28</td>
                  <td>08.12.2013</td>
                  <td>06:31</td>
                  <td>08.12.2013</td>
                  <td>00:03</td>
                  <td>Brzi</td>
                  <td></td>
                  <td><input type="button" class="btn btn-normal" value="Naruci"></td>
                </tr>
              </tbody>
            </table>
          </div>
           
          <ul class="pagination pagination-centered">
            <li><a href="#">&laquo;</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
          </ul>
        </div>

         <div class="row">
             
        </div>
      </div>    
       <hr>

      <footer>
        <p>Dizajnirao Slaven Dragičević 2013</p>
      </footer>
    </div> <!-- /container -->
    

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script>
      var dateToday = new Date();
      $(function() {
        $( "#datepicker" ).datepicker({
            minDate: dateToday
        });
      });
    </script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>
